name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security checks weekly on Mondays at 2 AM UTC
    - cron: '0 2 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up virtual environment
      run: |
        uv sync --dev

    - name: Run safety check for known security vulnerabilities
      run: |
        uv run pip install safety
        uv run safety check --json || echo "Safety check completed with warnings"

    - name: Run bandit security linter
      run: |
        uv run pip install bandit[toml]
        uv run bandit -r src/ -f json -o bandit-report.json || echo "Bandit completed with findings"
        uv run bandit -r src/ -f txt

    - name: Upload security artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
        retention-days: 30